[[sites]]
domain = 'www.example.com'

[[sites.headers]]
for = '/*'

[sites.headers.values]
Cache-Control = 'public'
Referrer-Policy = 'strict-origin-when-cross-origin'
Strict-Transport-Security = 'max-age=31536000; includeSubDomains; preload'

[[sites.headers]]
for = '*.css'

[sites.headers.values]
Cache-Control = 'public'
Referrer-Policy = 'strict-origin-when-cross-origin'
Strict-Transport-Security = 'max-age=31536000; includeSubDomains; preload'